// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: include/osh-core/sensorhub-service-consys/src/main/proto/observation.proto

package org.sensorhub.impl.service.consys.obs.proto;

public final class Observation {
  private Observation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OshObservationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:obs.OshObservation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string datastreamId = 2;</code>
     * @return The datastreamId.
     */
    java.lang.String getDatastreamId();
    /**
     * <code>string datastreamId = 2;</code>
     * @return The bytes for datastreamId.
     */
    com.google.protobuf.ByteString
        getDatastreamIdBytes();

    /**
     * <code>string foiId = 3;</code>
     * @return The foiId.
     */
    java.lang.String getFoiId();
    /**
     * <code>string foiId = 3;</code>
     * @return The bytes for foiId.
     */
    com.google.protobuf.ByteString
        getFoiIdBytes();

    /**
     * <code>string phenomenonTime = 4;</code>
     * @return The phenomenonTime.
     */
    java.lang.String getPhenomenonTime();
    /**
     * <code>string phenomenonTime = 4;</code>
     * @return The bytes for phenomenonTime.
     */
    com.google.protobuf.ByteString
        getPhenomenonTimeBytes();

    /**
     * <code>string resultTime = 5;</code>
     * @return The resultTime.
     */
    java.lang.String getResultTime();
    /**
     * <code>string resultTime = 5;</code>
     * @return The bytes for resultTime.
     */
    com.google.protobuf.ByteString
        getResultTimeBytes();

    /**
     * <code>.obs.Results results = 6;</code>
     * @return Whether the results field is set.
     */
    boolean hasResults();
    /**
     * <code>.obs.Results results = 6;</code>
     * @return The results.
     */
    org.sensorhub.impl.service.consys.obs.proto.Observation.Results getResults();
    /**
     * <code>.obs.Results results = 6;</code>
     */
    org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder getResultsOrBuilder();
  }
  /**
   * Protobuf type {@code obs.OshObservation}
   */
  public static final class OshObservation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:obs.OshObservation)
      OshObservationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OshObservation.newBuilder() to construct.
    private OshObservation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OshObservation() {
      id_ = "";
      datastreamId_ = "";
      foiId_ = "";
      phenomenonTime_ = "";
      resultTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OshObservation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_OshObservation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_OshObservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.class, org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATASTREAMID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object datastreamId_ = "";
    /**
     * <code>string datastreamId = 2;</code>
     * @return The datastreamId.
     */
    @java.lang.Override
    public java.lang.String getDatastreamId() {
      java.lang.Object ref = datastreamId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datastreamId_ = s;
        return s;
      }
    }
    /**
     * <code>string datastreamId = 2;</code>
     * @return The bytes for datastreamId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDatastreamIdBytes() {
      java.lang.Object ref = datastreamId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datastreamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOIID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object foiId_ = "";
    /**
     * <code>string foiId = 3;</code>
     * @return The foiId.
     */
    @java.lang.Override
    public java.lang.String getFoiId() {
      java.lang.Object ref = foiId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foiId_ = s;
        return s;
      }
    }
    /**
     * <code>string foiId = 3;</code>
     * @return The bytes for foiId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFoiIdBytes() {
      java.lang.Object ref = foiId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foiId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHENOMENONTIME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phenomenonTime_ = "";
    /**
     * <code>string phenomenonTime = 4;</code>
     * @return The phenomenonTime.
     */
    @java.lang.Override
    public java.lang.String getPhenomenonTime() {
      java.lang.Object ref = phenomenonTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phenomenonTime_ = s;
        return s;
      }
    }
    /**
     * <code>string phenomenonTime = 4;</code>
     * @return The bytes for phenomenonTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhenomenonTimeBytes() {
      java.lang.Object ref = phenomenonTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phenomenonTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTTIME_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object resultTime_ = "";
    /**
     * <code>string resultTime = 5;</code>
     * @return The resultTime.
     */
    @java.lang.Override
    public java.lang.String getResultTime() {
      java.lang.Object ref = resultTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultTime_ = s;
        return s;
      }
    }
    /**
     * <code>string resultTime = 5;</code>
     * @return The bytes for resultTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultTimeBytes() {
      java.lang.Object ref = resultTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTS_FIELD_NUMBER = 6;
    private org.sensorhub.impl.service.consys.obs.proto.Observation.Results results_;
    /**
     * <code>.obs.Results results = 6;</code>
     * @return Whether the results field is set.
     */
    @java.lang.Override
    public boolean hasResults() {
      return results_ != null;
    }
    /**
     * <code>.obs.Results results = 6;</code>
     * @return The results.
     */
    @java.lang.Override
    public org.sensorhub.impl.service.consys.obs.proto.Observation.Results getResults() {
      return results_ == null ? org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance() : results_;
    }
    /**
     * <code>.obs.Results results = 6;</code>
     */
    @java.lang.Override
    public org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder getResultsOrBuilder() {
      return results_ == null ? org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance() : results_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datastreamId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datastreamId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foiId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, foiId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phenomenonTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phenomenonTime_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resultTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resultTime_);
      }
      if (results_ != null) {
        output.writeMessage(6, getResults());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datastreamId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datastreamId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foiId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, foiId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(phenomenonTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phenomenonTime_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resultTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resultTime_);
      }
      if (results_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getResults());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation)) {
        return super.equals(obj);
      }
      org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation other = (org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getDatastreamId()
          .equals(other.getDatastreamId())) return false;
      if (!getFoiId()
          .equals(other.getFoiId())) return false;
      if (!getPhenomenonTime()
          .equals(other.getPhenomenonTime())) return false;
      if (!getResultTime()
          .equals(other.getResultTime())) return false;
      if (hasResults() != other.hasResults()) return false;
      if (hasResults()) {
        if (!getResults()
            .equals(other.getResults())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + DATASTREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getDatastreamId().hashCode();
      hash = (37 * hash) + FOIID_FIELD_NUMBER;
      hash = (53 * hash) + getFoiId().hashCode();
      hash = (37 * hash) + PHENOMENONTIME_FIELD_NUMBER;
      hash = (53 * hash) + getPhenomenonTime().hashCode();
      hash = (37 * hash) + RESULTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getResultTime().hashCode();
      if (hasResults()) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResults().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code obs.OshObservation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:obs.OshObservation)
        org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_OshObservation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_OshObservation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.class, org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.Builder.class);
      }

      // Construct using org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        datastreamId_ = "";
        foiId_ = "";
        phenomenonTime_ = "";
        resultTime_ = "";
        results_ = null;
        if (resultsBuilder_ != null) {
          resultsBuilder_.dispose();
          resultsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_OshObservation_descriptor;
      }

      @java.lang.Override
      public org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation getDefaultInstanceForType() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.getDefaultInstance();
      }

      @java.lang.Override
      public org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation build() {
        org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation buildPartial() {
        org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation result = new org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.datastreamId_ = datastreamId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.foiId_ = foiId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.phenomenonTime_ = phenomenonTime_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.resultTime_ = resultTime_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.results_ = resultsBuilder_ == null
              ? results_
              : resultsBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation) {
          return mergeFrom((org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation other) {
        if (other == org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDatastreamId().isEmpty()) {
          datastreamId_ = other.datastreamId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getFoiId().isEmpty()) {
          foiId_ = other.foiId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPhenomenonTime().isEmpty()) {
          phenomenonTime_ = other.phenomenonTime_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getResultTime().isEmpty()) {
          resultTime_ = other.resultTime_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasResults()) {
          mergeResults(other.getResults());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                datastreamId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                foiId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                phenomenonTime_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                resultTime_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getResultsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object datastreamId_ = "";
      /**
       * <code>string datastreamId = 2;</code>
       * @return The datastreamId.
       */
      public java.lang.String getDatastreamId() {
        java.lang.Object ref = datastreamId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          datastreamId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string datastreamId = 2;</code>
       * @return The bytes for datastreamId.
       */
      public com.google.protobuf.ByteString
          getDatastreamIdBytes() {
        java.lang.Object ref = datastreamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datastreamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string datastreamId = 2;</code>
       * @param value The datastreamId to set.
       * @return This builder for chaining.
       */
      public Builder setDatastreamId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        datastreamId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string datastreamId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatastreamId() {
        datastreamId_ = getDefaultInstance().getDatastreamId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string datastreamId = 2;</code>
       * @param value The bytes for datastreamId to set.
       * @return This builder for chaining.
       */
      public Builder setDatastreamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        datastreamId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object foiId_ = "";
      /**
       * <code>string foiId = 3;</code>
       * @return The foiId.
       */
      public java.lang.String getFoiId() {
        java.lang.Object ref = foiId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          foiId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string foiId = 3;</code>
       * @return The bytes for foiId.
       */
      public com.google.protobuf.ByteString
          getFoiIdBytes() {
        java.lang.Object ref = foiId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          foiId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string foiId = 3;</code>
       * @param value The foiId to set.
       * @return This builder for chaining.
       */
      public Builder setFoiId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        foiId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string foiId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFoiId() {
        foiId_ = getDefaultInstance().getFoiId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string foiId = 3;</code>
       * @param value The bytes for foiId to set.
       * @return This builder for chaining.
       */
      public Builder setFoiIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        foiId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object phenomenonTime_ = "";
      /**
       * <code>string phenomenonTime = 4;</code>
       * @return The phenomenonTime.
       */
      public java.lang.String getPhenomenonTime() {
        java.lang.Object ref = phenomenonTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phenomenonTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phenomenonTime = 4;</code>
       * @return The bytes for phenomenonTime.
       */
      public com.google.protobuf.ByteString
          getPhenomenonTimeBytes() {
        java.lang.Object ref = phenomenonTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phenomenonTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phenomenonTime = 4;</code>
       * @param value The phenomenonTime to set.
       * @return This builder for chaining.
       */
      public Builder setPhenomenonTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phenomenonTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string phenomenonTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhenomenonTime() {
        phenomenonTime_ = getDefaultInstance().getPhenomenonTime();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string phenomenonTime = 4;</code>
       * @param value The bytes for phenomenonTime to set.
       * @return This builder for chaining.
       */
      public Builder setPhenomenonTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phenomenonTime_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object resultTime_ = "";
      /**
       * <code>string resultTime = 5;</code>
       * @return The resultTime.
       */
      public java.lang.String getResultTime() {
        java.lang.Object ref = resultTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resultTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resultTime = 5;</code>
       * @return The bytes for resultTime.
       */
      public com.google.protobuf.ByteString
          getResultTimeBytes() {
        java.lang.Object ref = resultTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resultTime = 5;</code>
       * @param value The resultTime to set.
       * @return This builder for chaining.
       */
      public Builder setResultTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        resultTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string resultTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultTime() {
        resultTime_ = getDefaultInstance().getResultTime();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string resultTime = 5;</code>
       * @param value The bytes for resultTime to set.
       * @return This builder for chaining.
       */
      public Builder setResultTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        resultTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private org.sensorhub.impl.service.consys.obs.proto.Observation.Results results_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.sensorhub.impl.service.consys.obs.proto.Observation.Results, org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder, org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder> resultsBuilder_;
      /**
       * <code>.obs.Results results = 6;</code>
       * @return Whether the results field is set.
       */
      public boolean hasResults() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.obs.Results results = 6;</code>
       * @return The results.
       */
      public org.sensorhub.impl.service.consys.obs.proto.Observation.Results getResults() {
        if (resultsBuilder_ == null) {
          return results_ == null ? org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance() : results_;
        } else {
          return resultsBuilder_.getMessage();
        }
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      public Builder setResults(org.sensorhub.impl.service.consys.obs.proto.Observation.Results value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          results_ = value;
        } else {
          resultsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      public Builder setResults(
          org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          results_ = builderForValue.build();
        } else {
          resultsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      public Builder mergeResults(org.sensorhub.impl.service.consys.obs.proto.Observation.Results value) {
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            results_ != null &&
            results_ != org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance()) {
            getResultsBuilder().mergeFrom(value);
          } else {
            results_ = value;
          }
        } else {
          resultsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      public Builder clearResults() {
        bitField0_ = (bitField0_ & ~0x00000020);
        results_ = null;
        if (resultsBuilder_ != null) {
          resultsBuilder_.dispose();
          resultsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      public org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder getResultsBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getResultsFieldBuilder().getBuilder();
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      public org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder getResultsOrBuilder() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilder();
        } else {
          return results_ == null ?
              org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance() : results_;
        }
      }
      /**
       * <code>.obs.Results results = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.sensorhub.impl.service.consys.obs.proto.Observation.Results, org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder, org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder> 
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.sensorhub.impl.service.consys.obs.proto.Observation.Results, org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder, org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder>(
                  getResults(),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:obs.OshObservation)
    }

    // @@protoc_insertion_point(class_scope:obs.OshObservation)
    private static final org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation();
    }

    public static org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OshObservation>
        PARSER = new com.google.protobuf.AbstractParser<OshObservation>() {
      @java.lang.Override
      public OshObservation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OshObservation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OshObservation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sensorhub.impl.service.consys.obs.proto.Observation.OshObservation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:obs.Results)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getValues();
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getValuesMap();
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    /* nullable */
java.lang.String getValuesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    java.lang.String getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code obs.Results}
   */
  public static final class Results extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:obs.Results)
      ResultsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Results.newBuilder() to construct.
    private Results(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Results() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Results();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_Results_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_Results_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensorhub.impl.service.consys.obs.proto.Observation.Results.class, org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_Results_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> values_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }
    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override
    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getValuesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; values = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, values__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sensorhub.impl.service.consys.obs.proto.Observation.Results)) {
        return super.equals(obj);
      }
      org.sensorhub.impl.service.consys.obs.proto.Observation.Results other = (org.sensorhub.impl.service.consys.obs.proto.Observation.Results) obj;

      if (!internalGetValues().equals(
          other.internalGetValues())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sensorhub.impl.service.consys.obs.proto.Observation.Results prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code obs.Results}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:obs.Results)
        org.sensorhub.impl.service.consys.obs.proto.Observation.ResultsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_Results_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_Results_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sensorhub.impl.service.consys.obs.proto.Observation.Results.class, org.sensorhub.impl.service.consys.obs.proto.Observation.Results.Builder.class);
      }

      // Construct using org.sensorhub.impl.service.consys.obs.proto.Observation.Results.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableValues().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.internal_static_obs_Results_descriptor;
      }

      @java.lang.Override
      public org.sensorhub.impl.service.consys.obs.proto.Observation.Results getDefaultInstanceForType() {
        return org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance();
      }

      @java.lang.Override
      public org.sensorhub.impl.service.consys.obs.proto.Observation.Results build() {
        org.sensorhub.impl.service.consys.obs.proto.Observation.Results result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sensorhub.impl.service.consys.obs.proto.Observation.Results buildPartial() {
        org.sensorhub.impl.service.consys.obs.proto.Observation.Results result = new org.sensorhub.impl.service.consys.obs.proto.Observation.Results(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.sensorhub.impl.service.consys.obs.proto.Observation.Results result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.values_ = internalGetValues();
          result.values_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sensorhub.impl.service.consys.obs.proto.Observation.Results) {
          return mergeFrom((org.sensorhub.impl.service.consys.obs.proto.Observation.Results)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sensorhub.impl.service.consys.obs.proto.Observation.Results other) {
        if (other == org.sensorhub.impl.service.consys.obs.proto.Observation.Results.getDefaultInstance()) return this;
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                values__ = input.readMessage(
                    ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableValues().getMutableMap().put(
                    values__.getKey(), values__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> values_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableValues() {
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return values_;
      }
      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override
      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getValuesOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearValues() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableValues() {
        bitField0_ |= 0x00000001;
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      public Builder putValues(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; values = 1;</code>
       */
      public Builder putAllValues(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:obs.Results)
    }

    // @@protoc_insertion_point(class_scope:obs.Results)
    private static final org.sensorhub.impl.service.consys.obs.proto.Observation.Results DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sensorhub.impl.service.consys.obs.proto.Observation.Results();
    }

    public static org.sensorhub.impl.service.consys.obs.proto.Observation.Results getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Results>
        PARSER = new com.google.protobuf.AbstractParser<Results>() {
      @java.lang.Override
      public Results parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Results> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Results> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sensorhub.impl.service.consys.obs.proto.Observation.Results getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obs_OshObservation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obs_OshObservation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obs_Results_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obs_Results_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_obs_Results_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_obs_Results_ValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJinclude/osh-core/sensorhub-service-con" +
      "sys/src/main/proto/observation.proto\022\003ob" +
      "s\"\214\001\n\016OshObservation\022\n\n\002id\030\001 \001(\t\022\024\n\014data" +
      "streamId\030\002 \001(\t\022\r\n\005foiId\030\003 \001(\t\022\026\n\016phenome" +
      "nonTime\030\004 \001(\t\022\022\n\nresultTime\030\005 \001(\t\022\035\n\007res" +
      "ults\030\006 \001(\0132\014.obs.Results\"b\n\007Results\022(\n\006v" +
      "alues\030\001 \003(\0132\030.obs.Results.ValuesEntry\032-\n" +
      "\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001B:\n+org.sensorhub.impl.service.consy" +
      "s.obs.protoB\013Observationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_obs_OshObservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_obs_OshObservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obs_OshObservation_descriptor,
        new java.lang.String[] { "Id", "DatastreamId", "FoiId", "PhenomenonTime", "ResultTime", "Results", });
    internal_static_obs_Results_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_obs_Results_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obs_Results_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_obs_Results_ValuesEntry_descriptor =
      internal_static_obs_Results_descriptor.getNestedTypes().get(0);
    internal_static_obs_Results_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_obs_Results_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
